import Head from "next/head";
import { Inter } from "next/font/google";
import {
  Box,
  Button,
  Card,
  Container,
  Group,
  Text,
  Title,
} from "@mantine/core";
import { useFavoriteEmojis } from "@/utils/use/useFavoriteEmojis";
import { EmojiDisplay } from "@/components/emojiDisplay";
import { Emoji } from "@/model/emoji/emoji";
import { GridModel } from "@/model/grid/grid";
import { GridCellModel } from "@/model/grid/gridCell";
import { useState } from "react";
import { CanvasRow } from "@/components/canvasRow";
import { CanvasGrid } from "@/components/canvasGrid";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const emoji1 = new Emoji(
    "shortcode1",
    "https://raw.githubusercontent.com/Lokuyow/Lokuyow.github.io/main/images/nostr/emoji/kami.png"
  );
  const emoji2 = new Emoji(
    "shortcode2",
    "https://raw.githubusercontent.com/Lokuyow/Lokuyow.github.io/main/images/nostr/emoji/nazo.png"
  );
  const emoji3 = new Emoji(
    "shortcode3",
    "https://raw.githubusercontent.com/Lokuyow/Lokuyow.github.io/main/images/nostr/emoji/igyo.png"
  );
  const cell1 = new GridCellModel();
  cell1.setEmoji(emoji1);

  const { error, data, isLoading } = useFavoriteEmojis();
  const [grid, setGrid] = useState<GridModel>(GridModel.fromSize(2, 2));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Title order={2}>絵文字コネコネ</Title>
          <Text my={5}>
            グリッド上で絵文字をポチポチして投稿を作成できるツールです。
            <br />
            現状では縦:横が1:1の絵文字にのみ対応しており、それ以外を使うとバグります。
            <br />
            NIP-07にリレーと秘密鍵が登録してある状態でのみ使用可能です。
          </Text>
          <Text my={5}>
            設定したいセルにカーソルを合わせると選択やリセットなどのメニューが出てきます。
            セルを選択した上で、ページ下に表示されるお気に入り絵文字をクリックすることで、グリッドに絵文字を設定可能です。
            <br />
            eと表示されているセルは空白判定で、青いセルが現在選択中のセルです。
            <br />
            空白は勝手に保管されます。
          </Text>
          <Card my="lg" shadow="sm" padding="lg" radius="md" withBorder>
            <Title order={3}>編集</Title>
            <Button
              onClick={() => {
                setGrid(grid.setAt(0, 0, emoji1));
              }}
            >
              hogehoge
            </Button>
            <Box
              style={{
                display: "flex",
              }}
            ></Box>
            <CanvasGrid grid={grid} setGrid={setGrid} />
          </Card>
          <Card my="lg" shadow="sm" padding="lg" radius="md" withBorder>
            <Title order={3}>プレビュー</Title>
            hoge
          </Card>
          {data == undefined ? (
            error !== undefined ? (
              <Text>エラー発生！</Text>
            ) : (
              <Text>読込中</Text>
            )
          ) : (
            <>
              {data!.map((list) => (
                <Card
                  my="lg"
                  shadow="sm"
                  padding="lg"
                  radius="md"
                  withBorder
                  key={`${list.title}${list.author}`}
                >
                  <Title order={5}>{list.title ?? list.identifier}</Title>
                  <Group mt="sm">
                    {list.emojiList.map((elem) => (
                      <EmojiDisplay
                        emoji={elem}
                        key={`${elem.url}${elem.shortcode}`}
                        onClick={() => console.log(elem.shortcode)}
                      />
                    ))}
                  </Group>
                </Card>
              ))}
            </>
          )}
        </Container>
      </main>
    </>
  );
}
